from collections.abc import Iterable
from enum import StrEnum

class _Available(StrEnum):
    @classmethod
    def names(cls) -> Iterable[str]:
        for item in cls:
            yield item.name

class AvailableRotor(_Available):
    IC = 'DMTWSILRUYQNKFEJCAZBPGXOHV'
    IIC = 'HQZGPJTMOBLNCIFDYAWVEUSRKX'
    IIIC = 'UQNTLSZFMREHDPXKIBVYGJCWOA'
    I = 'JGDQOXUSCAMIFRVTPNEWKBLZYH'
    II = 'NTZPSFBOKMWRCJDIVLAEYUXHGQ'
    III = 'JVIUBHTCDYAKEQZPOSGXNRMWFL'
    IK = 'PEZUOHXSCVFMTBGLRINQJWAYDK'
    IIK = 'ZOUESYDKFWPCIQXHMVBLGNJRAT'
    IIIK = 'EHRVXGAOBQUSIMZFLYNWKTPDJC'
    I1930 = 'EKMFLGDQVZNTOWYHXUSPAIBRCJ'
    II1930 = 'AJDKSIRUXBLHWTMCQGZNPYFVOE'
    III1930 = 'BDFHJLCPRTXVZNYEIWGAKMUSQO'
    IV1938 = 'ESOVPZJAYQUIRHXLNFTGKDCMWB'
    V1938 = 'VZBRGITYUPSDNHLXAWMJQOFECK'
    VI1939 = 'JPGVOUMFYQBENHZRDKASXLICTW'
    VII1939 = 'NZJHGRCXMYSWBOUFAIVLPEKQDT'
    VIII1939 = 'FKQHTLXOCBJSPDZRAMEWNIUYGV'

class AvailableReflector(_Available):
    UKW = 'QYHOGNECVPUZTFDJAXWMKISRBL'
    ETW = 'QWERTZUIOASDFGHJKPYXCVBNML'
    UKWK = 'IMETCGFRAYSQBZXWLHKDVUPOJN'
    ETWK = 'QWERTZUIOASDFGHJKPYXCVBNML'
    BETA = 'LEYJVCNIXWPBQMDRTAKZGFUHOS'
    GAMMA = 'FSOKANUERHMBTIYCWLQPZXVGJD'
    REFA = 'EJMZALYXVBWFCRQUONTSPIKHGD'
    REFB = 'YRUHQSLDPXNGOKMIEBFZCWVJAT'
    REFC = 'FVPJIAOYEDRZXWGCTKUQSBNMHL'
    REFBTHIN = 'ENKQAUYWJICOPBLMDXZVFTHRGS'
    REFCTTHIN = 'RDOBJNTKVEHMLFCWZAXGYIPSUQ'
    REFETW = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'